networks:
  integration_network:
    external: true 
services:
  db_pg18:
    image: pgvector/pgvector:pg18-trixie
    container_name: pg18_vector_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pgvector_db
    ports:
      - "5433:5432"
    volumes:
      - postgres18_data:/var/lib/postgresql

    networks:
      - integration_network

volumes:
   postgres18_data: